# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterCS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='semestercs',
            name='str',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Erudite.Stream'),
        ),
    ]
