# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Erudite', '0003_semesterece_subjectece'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectcs',
            name='link',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectece',
            name='link',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
